"""initial

Revision ID: 2515affc2f76
Revises: 
Create Date: 2019-10-29 19:55:19.820977+00:00

"""
from alembic import op
import sqlalchemy as sa

from alar.models import UserRight
from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision = '2515affc2f76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('rights', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('login')
    )
    op.bulk_insert(user_table,
                   [{'login': 'admin',
                     'password': generate_password_hash('admin'),
                     'rights': UserRight.VIEW.value | UserRight.CREATE.value | UserRight.UPDATE.value | UserRight.DELETE.value}, ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
